name: Build

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install dependencies
        run: |
          chmod +x ./ci/before-script.sh
          ./ci/before-script.sh
          python -m pip install --upgrade pip
          pip install pynose

      - name: Run tests
        run: nosetests -w tests
